services:
  - type: web
    name: openhands-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SERVE_FRONTEND
        value: false
      - key: DEBUG
        value: false
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health