services:
  - type: web
    name: openhands-novel-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m openhands.server.listen --host 0.0.0.0 --port $PORT
    envVars:
      # Server Configuration
      - key: PORT
        sync: false
      - key: HOST
        value: "0.0.0.0"
      
      # OpenRouter API Configuration (Primary for Novel Writing)
      - key: OPENROUTER_API_KEY
        sync: false
      - key: LLM_API_KEY
        sync: false
      - key: LLM_BASE_URL
        value: "https://openrouter.ai/api/v1"
      
      # Default Model Configuration
      - key: LLM_MODEL
        value: "openrouter/anthropic/claude-3-haiku-20240307"
      
      # Novel Writing Mode Models
      - key: NOVEL_WRITING_BUDGET_MODEL
        value: "openrouter/anthropic/claude-3-haiku-20240307"
      - key: NOVEL_WRITING_PREMIUM_MODEL
        value: "openrouter/anthropic/claude-3-opus-20240229"
      
      # OpenRouter Headers
      - key: OR_SITE_URL
        value: "https://docs.all-hands.dev/"
      - key: OR_APP_NAME
        value: "OpenHands-NovelWriting"
      
      # Session Configuration
      - key: SESSION_API_KEY
        sync: false
      
      # Basic Configuration
      - key: SERVE_FRONTEND
        value: "false"
      - key: DEBUG
        value: "false"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: LOG_LEVEL
        value: "info"
      
      # Runtime Configuration
      - key: RUNTIME
        value: "eventstream"
      - key: DEFAULT_AGENT
        value: "CodeActAgent"
      - key: MAX_CONCURRENT_CONVERSATIONS
        value: "5"
      
      # Security Configuration
      - key: SECURITY_CONFIRMATION_MODE
        value: "false"
      
      # File Storage
      - key: FILE_STORE_PATH
        value: "/tmp/openhands_storage"
      
      # Sandbox Configuration
      - key: SANDBOX_TIMEOUT
        value: "120"
      - key: SANDBOX_USER_ID
        value: "1000"
      
      # Disable unnecessary features
      - key: ENABLE_AUTO_LINT
        value: "false"
      - key: ENABLE_AUTO_TEST
        value: "false"
    
    healthCheckPath: /api/health
    
    # Resource allocation for novel writing workloads
    plan: starter
    
    # Auto-deploy from main branch
    autoDeploy: true