services:
  - type: web
    name: openhands-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PORT
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DEBUG
        value: "false"
      - key: SERVE_FRONTEND
        value: "false"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
    healthCheckPath: /api/health