name: 🚀 Deploy to Minatoz997/Backend66

on:
  workflow_dispatch:
    inputs:
      clean_deploy:
        description: 'Clean deploy (remove all files first)'
        required: true
        default: true
        type: boolean
      hf_token:
        description: 'HF Token (or use HF_TOKEN secret)'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 📦 Install dependencies
      run: |
        pip install huggingface_hub
        
    - name: 🧹 Clean deploy to Minatoz997/Backend66
      if: ${{ inputs.clean_deploy }}
      env:
        HF_TOKEN: ${{ inputs.hf_token || secrets.HF_TOKEN }}
      run: |
        python deploy_to_hf.py --space-name "Minatoz997/Backend66"
        
    - name: 📤 Regular deploy to Minatoz997/Backend66
      if: ${{ !inputs.clean_deploy }}
      env:
        HF_TOKEN: ${{ inputs.hf_token || secrets.HF_TOKEN }}
      run: |
        # Install huggingface_hub CLI
        pip install --upgrade huggingface_hub[cli]
        
        # Upload essential files only
        echo "📋 Uploading essential files to Minatoz997/Backend66..."
        huggingface-cli upload Minatoz997/Backend66 app.py --repo-type=space
        huggingface-cli upload Minatoz997/Backend66 requirements.txt --repo-type=space
        huggingface-cli upload Minatoz997/Backend66 Dockerfile --repo-type=space
        huggingface-cli upload Minatoz997/Backend66 README.md --repo-type=space
        huggingface-cli upload Minatoz997/Backend66 PERSONAL_TOKEN_GUIDE.md --repo-type=space
        huggingface-cli upload Minatoz997/Backend66 README_HF_DEPLOYMENT.md --repo-type=space
        huggingface-cli upload Minatoz997/Backend66 openhands/ --repo-type=space
        huggingface-cli upload Minatoz997/Backend66 microagents/ --repo-type=space
        
    - name: ✅ Deployment complete
      run: |
        echo "🎉 Deployment to Minatoz997/Backend66 successful!"
        echo "🌐 Your space: https://huggingface.co/spaces/Minatoz997/Backend66"
        echo "📊 Logs: https://huggingface.co/spaces/Minatoz997/Backend66?logs=container"
        echo "⏱️  Build will start automatically (5-10 minutes)"
        echo ""
        echo "🔧 NEXT STEPS:"
        echo "1. Go to: https://huggingface.co/spaces/Minatoz997/Backend66/settings"
        echo "2. Set environment variables:"
        echo "   - LLM_API_KEY=your_openrouter_key"
        echo "   - PERSONAL_ACCESS_TOKEN=backend-for-us-2024"
        echo "3. Wait for build to complete"
        echo "4. Test: https://minatoz997-backend66.hf.space/health"
        echo ""
        echo "💕 Enjoy your clean personal AI backend!"
