name: Mirror GitHub Repo to HF Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Sync only /openhands folder to Hugging Face
        run: |
          rsync -av --delete ./openhands/ ./repo/

      - name: Push to Hugging Face
        uses: huggingface/huggingface_hub_action@v0.1
        with:
          repo_id: Minatoz997/Backend66
          repo_type: space
          token: ${{ secrets.HF_TOKEN }}
